version: '3'

services:
  master:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MasterSettings__SlaveUri=http://slave
    ports:
      - "5000:80"

  slave:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
  integrationtests:
    volumes:
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=/tests/test-results.xml