version: '3'

services:
    master:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - MasterSettings__SlaveUri=http://slave
      ports:
        - "5000:80"

    slave:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "5001:80"