version: '3'

services:
  master:
    image: ramontc/master:v1
    build:
      context: ./Master
      dockerfile: Dockerfile

  slave:
    image: ramontc/slave:v1
    build:
      context: ./Slave
      dockerfile: Dockerfile
