version: '3.4'

services:
  master:
    image: master
    build:
      context: .
      dockerfile: Master/Dockerfile

  slave:
    image: slave
    build:
      context: .
      dockerfile: Slave/Dockerfile

  master-tests:
    image: master-tests
    build:
      context: .
      dockerfile: Master/Dockerfile      
      target: test
    volumes: 
      - ${BUILD_ARTIFACTSTAGINGDIRECTORY:-./tests-results/}:/tests