version: '3'

services:
  master:
    image: master
    build:
      context: ./Master
      dockerfile: Dockerfile

  slave:
    image: slave
    build:
      context: ./Slave
      dockerfile: Dockerfile
