version: '3.4'

services:
    master:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - MasterSettings__SlaveUri=http://slave
      ports:
        - "5000:80"

    slave:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "5001:80"

    master-tests:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development      
      entrypoint:
        - dotnet
        - test
        - --logger
        - trx;LogFileName=/tests/test-results.xml