version: '3'

services:
  master:
    image: ramontc/master
    build:
      context: ./Master
      dockerfile: Dockerfile

  slave:
    image: ramontc/slave
    build:
      context: ./Slave
      dockerfile: Dockerfile
